name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Node 16.16.0
      uses: actions/setup-node@v1
      with:
        node-version: 16.16.0
    - name: npm install
      run: npm i
    - name: copy files to server
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.SSH_HOST }}
        PORT: ${{ secrets.SSH_PORT }}
        USERNAME: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        target: ${{ secrets.SSH_TARGET }}
        source: "./*"
